### ISSUE TITLE
Promise Support

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [berniegp/mock-xmlhttprequest#2]
It would be really helpful if promise support were added so I could more simply do the following:

```javascript
const xhr = await new Promise((resolve, reject) => {
  MockXMLHttpRequest.onSend = resolve
  form.dispatchEvent(new Event('submit'))
  setTimeout(() => reject(new Error('timed out')), 50)
})
```

**Comment by berniegp** [comment]
What is missing exactly for such code to work?

**Comment by BebeSparkelSparkel** [comment]
I think it would be helpful if I could be able to perform the following
```javascript
const xhr = await MockXMLHttpRequest.triggerSend(triggerFunction [, timeout])
```
This way I could cleanly get the xhr object in my async function.  
triggerFunction would be a function that should trigger the MockXMLHttpRequest.send method to be called.  
Lastly, there could be an optional timeout that would cause the await to reject and throw a timeout error.  
It seems like that would be very helpful and allow my following test to be simplified from:
```javascript
  it('post request should be made on form submit', async function() {
    const form_type = 'form1'
    const { window, document, Event } = await load_page(form_type)
    const form = document.querySelector('form')

    all_good(document, form_type)

    window.XMLHttpRequest = MockXMLHttpRequest
    window.eval('XMLHttpRequest = window.XMLHttpRequest')

    const xhr = await new Promise((resolve, reject) => {
      MockXMLHttpRequest.onSend = resolve
      form.dispatchEvent(new Event('submit'))
      setTimeout(() => reject(new Error('timed out')), 50)
    })

    expect( xhr.method ).to.equalIgnoreCase('post')
    expect( xhr.body ).to.be.a('FormData')
```
to
```javascript
  it('post request should be made on form submit', async function() {
    const form_type = 'form1'
    const { window, document, Event } = await load_page(form_type)
    const form = document.querySelector('form')

    all_good(document, form_type)

    window.XMLHttpRequest = MockXMLHttpRequest
    window.eval('XMLHttpRequest = window.XMLHttpRequest')

    const xhr = await MockXMLHttpRequest.triggerSend(
      () => form.dispatchEvent(new Event('submit')),
      50
    )

    expect( xhr.method ).to.equalIgnoreCase('post')
    expect( xhr.body ).to.be.a('FormData')
```

**Comment by berniegp** [comment]
I haven't used `async/await` yet so I'm not very familiar with them. From what I understand, you want a helper function that returns a pre-configured promise that resolves itself when an XHR request is sent. While this is certainly useful, I'm not convinced (yet) that this kind of helper function should be included here as it's not directly related to XMLHttpRequest. In my opinion, this should be part of your testing code helpers since there can be many (too many) different ways to want to configure such a promise.

Also, this library doesn't currently require ES6 so this would at least require a major version release.

**Comment by BebeSparkelSparkel** [comment]
What you're saying makes sense.

async/await just makes promises easier to deal with, so ES6 isn't actually required.
Basically all the `MockXMLHttpRequest.triggerSend` would have to do is return a Promise that resolves when send is called.

```javascript
async function async_version() {
  try {
    const xhr = await MockXMLHttpRequest.triggerSend(triggerFunction [, timeout])
    console.log(xhr)
  } catch(err) {
    console.error(err)
  }
}

// Is basically the same as the promise code below
MockXMLHttpRequest.triggerSend(triggerFunction [, timeout])
  .then(xhr => {console.log(xhr)})
  .catch(err => {console.log(err)})
```


```

**Comment by berniegp** [comment]
Promises were added to the language in ECMAScript 6

**Comment by berniegp** [comment]
Promises were added to the language in ECMAScript 6

**Comment by BebeSparkelSparkel** [comment]
Thanks for pointing out that glaring mistake. I'll look at removing the promises that I put in my PR
