### ISSUE TITLE
upload progress event incomplete?

### ISSUE THREAD

**Issue by warpdesign** [berniegp/mock-xmlhttprequest#20]
**Is this issue a *feature* request or a *bug* report?**
bug report.

**What is the current behavior?**
When sending an upload progress event using `uploadProgress`, the event received looks like this:
>   progress Event {
>      type: 'progress',
>      loaded: 1000,
>      total: 0,
>      lengthComputable: false
>    }
total is always 0 and lengthComputable is also always 0 and there is no way to change that. In my tests I'd need to be able to set lengthComputable to true and total to the upload size.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Code being tested:

**What is the expected behavior?**
total and lengthComputable should be set when sending the progress event.

**Environment in which you encounter the issue:**
Node.js/jest.

- mock-xmlhttprequest version:6.1.1
- Node.js version: 12.18.2
- OS version: macOS 10.15.6

**Did this work in a previous version of mock-xmlhttprequest (which)?**
No idea.

**Do you intend to provide a pull request to address this issue?**

**Comment by berniegp** [comment]
The total size for the upload progress event is taken from the request body:

```js
  _getRequestBodySize() {
    if (!this.body) {
      return 0;
    }
    return this.body.size ? this.body.size : this.body.length;
  }
```

Without any more reproduction code I can't guess anything more about your issue.

**Comment by warpdesign** [comment]
Right now this is the code I'm using to send the XHR:

```js
    const formData = new FormData()
    const xhr = new XMLHttpRequest()
    formData.append('attachment', file)

    // progress handler
    xhr.upload.addEventListener(
      'progress',
      (e) => {
        if (e.lengthComputable) {
           // ...
        }
      },
      true
    )

    xhr.open('post', url)
    xhr.send(formData)
```

And this is how I am using mock-xmlhttprequest

```js
const MockXhr = MockXMLHttpRequest.newMockXhr()

MockXhr.onSend = (xhr) => {
  const responseHeaders = { 'Content-Type': 'application/json' }
  const response = JSON.stringify({  })
  // simulate progress event
  xhr.uploadProgress(1000)
  xhr.respond(200, responseHeaders, response)
}

global.XMLHttpRequest = MockXhr
```
How am I supposed to pass a length to the body? Shouldn't it be calculated by xhr itself? I am not setting it in my real app, yet the progress events I receive contain the `total` prop with total bytes size and `lengthComputable` is set to true.

Looking at the source code of mock-xmlhttprequest it seems it is expecting `body.size` or `body.length` to contain the size but since I am sending a FormData object I am not sure I can set a `size` or `length` property on the FormData instance.

**Comment by berniegp** [comment]
Now I get it. The code indeed doesn't handle computing the size of a `FormData` body currently. It seems pretty easy to add support for it though.

To help me move this along, what are you using to provide the `FormData` class? I don't think nodejs has native support for that class so I'd like to know which library you use to test it myself. Or are you running your tests in the browser with a native `FormData` object?

**Comment by berniegp** [comment]
I added support for `FormData` in a feature branch. Could you give it a try and let me know if it works?

This should get the right commit:
```
"dependencies": {
  "package": "git://github.com/berniegp/mock-xmlhttprequest.git#d7fe27ab239560bad02b76cb16cd074044e9df34"
}
```

I also added the `getRequestBodySize()` method which might be useful (check the readme).

**Comment by berniegp** [comment]
@warpdesign any news?

**Comment by warpdesign** [comment]
Sorry, didn't have time to try it sooner.

Just did a test with your formData branch and it works as expected. You can merge the branch and I'll be able to remove the hack I used for the length :)

Thank you!

**Comment by berniegp** [comment]
Thanks for the test! v6.2.0 is out now with the new feature
