### ISSUE TITLE
Individual Instances of MockXMLHttpRequest

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [berniegp/mock-xmlhttprequest#3]
Is it possible to create individual instances of the MockXMLHttpRequest object?

If not, it would be helpful since I have written my own cleanup method and I'm not sure if it is covering all the bases.

```javascript
afterEach(() => {
  MockXMLHttpRequest.onSend = undefined
  MockXMLHttpRequest.onCreate = undefined
})
```

Having an individual instance would ensure that each test would start with a fresh MockXMLHttpRequest object.

**Comment by berniegp** [comment]
Yes you can create individual instances of `MockXMLHttpRequest`. In fact, if you use this

```global.XMLHttpRequest = MockXMLHttpRequest;```

a new instance of `MockXMLHttpRequest` will be created each time an `XMLHttpRequest` is used. `MockXMLHttpRequest` is then the replacement prototype for new `XMLHttpRequest` instances.

`onSend` can be set per-instance instead of globally as described in the doc. I think you'd get the desired behavior with this. You can set an `onCreate` callback in your unit test that sets a local `onSend` function that does what you need.

`onCreate` by its nature however is unavoidably a "global" function. It doesn't make sense (to me at least) to have it any other way.

CommonJS states that multiple calls to `require('MockXMLHttpRequest')` will always return the same object so you're kind of stuck with a single global object there unless you clone it locally in your test. However, you have indeed covered all bases with your `afterEach` function.

**Comment by BebeSparkelSparkel** [comment]
Thanks for the info.

"onCreate by its nature however is unavoidably a "global" function." I think that this makes sense in a lot of cases, but I also think that it leaves room for the state of one test to be unintentionally transferred to another test.
It seems to me that you could allow `global.XMLHttpRequest = MockXMLHttpRequest;` to remain valid but also allow:
```javascript
global.XMLHttpRequest = new MockXMLHttpRequest({onCreate, onSend})
```

This would be helpful when a new `global` is created for every test.  
I am currently doing this with jsdom and the `afterEach` solution I presented above is a bit dicey since moch has a lot of layers from `describe`.

**Comment by berniegp** [comment]
`MockXMLHttpRequest` is currently a constructor function that replaces (or adds) the one for `XMLHttpRequest`. Code under test will then create `XMLHttpRequest` instances as usual (with `new XMLHttpRequest()`) which will actually create an instance of `MockXMLHttpRequest` instead. So I don<t see how this call could be implemented without breaking the current API:

```global.XMLHttpRequest = new MockXMLHttpRequest({onCreate, onSend})```

However, I see your point that it would be useful to have the possibility of better encapsulating the mock configuration in tests. I think moving the creation of the `MockXMLHttpRequest` function to a new configurable factory function would achieve this. What do you think of something like this:

```javascript
var MockXhrFactory = function(options)
{
  // return a new MockXhr constructor using options
}

// default constructor (no change compared to now)
var MockXhr = MockXhrFactory();

// give access to the MockXhrFactory
MockXhr.newInstance = MockXhrFactory;

module.exports = MockXhr;
```

**Comment by BebeSparkelSparkel** [comment]
Good point.

I think that would solve everything very nicely.

**Comment by berniegp** [comment]
I can have a look at this eventually. I'm aware that there is no "contributing" section, but if you have time to spare I'm ready to accept pull requests too.

**Comment by BebeSparkelSparkel** [comment]
I'm looking at your code and I do not think that your statement of "onSend can be set per-instance instead of globally as described in the doc" is true, because the global instance of onSend will also be called even if the instance's onSend is defined.

Is it a breaking change to make the second if and else if?

```javascript
  var xhr = this;
  if (typeof this.onSend === 'function') {
    // Save the callback in case it changes on the global object
    var instanceOnSend = this.onSend;
    setTimeout(function() {
      instanceOnSend.call(xhr, xhr);
    }, 0);
  }
  if (typeof MockXhr.onSend === 'function') {
    // Save the callback in case it changes on the global object
    var globalOnSend = MockXhr.onSend;
    setTimeout(function() {
      globalOnSend.call(xhr, xhr);
    }, 0);
  }
```

**Comment by berniegp** [comment]
Right. Well it all depends on how the mock is used. If you restrict your test code to the per-instance `onSend` then all is good.

I can see how some user tests would fail with using `else if`. I think some of my own would fail actually :)

**Comment by BebeSparkelSparkel** [comment]
Could you add a test case for the functionality that you are expecting for those two if cases so that I can ensure that my changes don't break what you are expecting?
