### ISSUE TITLE
Error thrown on computing string sizes in FormData.

### ISSUE THREAD

**Issue by lonelam** [berniegp/mock-xmlhttprequest#31]
**Is this issue a *feature* request or a *bug* report?**
# 🐛Bug Report
**What is the current behavior?**
The script throws exception when sending post request on mock scene.
![image](https://user-images.githubusercontent.com/16681599/179555524-94861498-f476-455d-85f0-cd49753c8073.png)

Inspecting stack trace of the error, the util function `getStringByteLength` in `src/Utils.js` seems using the native Blob to get the length of a string.
## 🪧Step to reproduce
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
```javascript
// inject mock-xmlhttprequest somewhere.
const formData = new FormData();
formData.append('name', 'some string in form');
axios.post('https://google.com/', formData, {}, {});
```
**What is the expected behavior?**
> Maybe it should not throw the error?
**Environment in which you encounter the issue:**
- mock-xmlhttprequest version: 7.0.4
- Chrome version: Version 103.0.5060.114 (Official Build) (x86_64)
- OS version: MacOS Big Sur

**Did this work in a previous version of mock-xmlhttprequest (which)?**
Have no idea about previous version of mock-xmlhttprequest.
**Do you intend to provide a pull request to address this issue?**
# 🚧fixing PR
The issue is clear: we should use `new Blob([string], {type: 'text/plain'});` to create a Blob according to latest 
[MDN document](https://developer.mozilla.org/en-US/docs/Web/API/Blob), I'm creating an PR for this bugfix.

**Comment by berniegp** [comment]
This is fixed in v8.0.0.
