### ISSUE TITLE
timeout attribute throw Mock usage error detected.

### ISSUE THREAD

**Issue by lyz810** [berniegp/mock-xmlhttprequest#37]
**Describe the bug**

**Steps to reproduce the behavior:**

**Expected behavior**

**Environment in which you encounter the issue:**
- mock-xmlhttprequest version:
- Node.js version:
- OS version:

**Additional context**

**Do you intend to provide a fix yourself?**

**Comment by berniegp** [comment]
Please provide information. I can't do anything with this
