### ISSUE TITLE
Using ArrayBuffer as body in request handler object gives TypeScript type error

### ISSUE THREAD

**Issue by petervdn** [berniegp/mock-xmlhttprequest#38]
**Describe the bug**
The body property seems to be typed as `string | undefined`, which does not allow me to set an `ArrayBuffer` as a response.

**Steps to reproduce the behavior:**
This request handler object gives a type error (`Type 'ArrayBuffer' is not assignable to type 'string'`)
```
newServer({
  get: [
    () => true,
    {
      status: 200,
      body: new ArrayBuffer(1024),
    },
  ],
})
```
Somewhat related: note that an example in the readme for the default value of that object also gives a type error when using that, since `body` should be `string | undefined`.
`{ status: 200, headers: {}, body: null, statusText: 'OK' }`

**Expected behavior**
Can get it to work by casting that request handler object `as any`, but I was expecting `ArrayBuffer` to be an allowed type. 

**Environment in which you encounter the issue:**
- mock-xmlhttprequest version: 8.0.0
- Node.js version: 16.14.0
- OS version: OSX 10.15.7

**Additional context**

**Do you intend to provide a fix yourself?**
No

**Comment by berniegp** [comment]
Thanks for the report!
