### ISSUE TITLE
Make all functions on `MockXhrServer` chainable

### ISSUE THREAD

**Issue by susnux** [berniegp/mock-xmlhttprequest#39]
**Is your feature request related to a problem? Please describe.**
Some functions like `setDefault404` or `addHandler` are chainable, but other are not, like `disableTimeout`.
It would be great if they would be consist chainable so that you can initialize the server in one chain.

**Describe the solution you'd like**
Make all configuration functions chainable

**Describe alternatives you've considered**
multiple lines like:
```js
server
    /*...*/
    .setDefault404()
server.disableTimeout()
server.install()
```

**Do you intend to provide a fix yourself?**
If you agree with this request I could try to submit a patch implementing this

**Comment by berniegp** [comment]
Thanks for the suggestion. Indeed that looks like an oversight.
I'd be happy to merge a pull request for this!
