### ISSUE TITLE
Mismatch between source code and published code

### ISSUE THREAD

**Issue by DanielSWolf** [berniegp/mock-xmlhttprequest#44]
**Describe the bug**

The code I get when installing `mock-xmlhttprequest` 8.1.0 from NPM doesn't seem to match the `v8.1.0` tag of your repository.

**Steps to reproduce the behavior:**

1. Check out the `v8.1.0` tag of your repository. You'll see the following code in `src/MockXhrRequest.ts`:

```ts
downloadProgress(transmitted: number, length: number) {
  this._responseReceiver.downloadProgress(this._requestData, transmitted, length);
}
```

2. Add `"mock-xmlhttprequest": "^8.1.0"` as a dependency to a local project and install it. Looking at `node_modules/mock-xmlhttprequest/package.json`, you'll see that `version` is indeed "8.1.0".

3. Now open `node_modules/mock-xmlhttprequest/dist/types/MockXhrRequest.d.ts`. You'll see the following signature:

```ts
downloadProgress(transmitted: number): void;
```

It seems that the `length` parameter is missing here, as well as in `node_modules/mock-xmlhttprequest/dist/cjs/MockXhrRequest.cjs`. For some reason, the signatures don't seem to match.

**Expected behavior**

I'd expect the signatures of the installed package to match those of the corresponding tag in the repo. In particular, I'd like to simulate upload and download progress events with current and total bytes, but the second parameter seems to be missing.

**Comment by berniegp** [comment]
This is surprising. Thanks for reporting this! I don't know how this could have happened.

I can't unpublish the current 8.1.0 version so I'll have to publish a new version.

**Comment by berniegp** [comment]
I suspect I had the wrong local Git state and had bits from the next branch (https://github.com/berniegp/mock-xmlhttprequest/tree/next)

In that branch I'm removing the `length` parameter to instead use the response's `Content-Length` header. This is more in line with the XHR spec. See this section: https://xhr.spec.whatwg.org/#the-send()-method and in particular this:
> Let length be the result of [extracting a length](https://fetch.spec.whatwg.org/#header-list-extract-a-length) from [this](https://webidl.spec.whatwg.org/#this)’s [response](https://xhr.spec.whatwg.org/#response)’s [header list](https://fetch.spec.whatwg.org/#concept-response-header-list).

Progress events on real `XMLHttpRequest`s require the `Content-Length` header so I believe it's misleading for this library to provide a way to produce them without the header.

I haven't completely decided on this change however. What do you think?

**Comment by berniegp** [comment]
I just published `v8.2.0` with a clean Git tree

**Comment by DanielSWolf** [comment]
> I just published `v8.2.0` with a clean Git tree

Could you check that? I see the `v8.2.0` tag in your repo, but I don't see [a corresponding NPM release](https://www.npmjs.com/package/mock-xmlhttprequest?activeTab=versions).

> Progress events on real `XMLHttpRequest`s require the `Content-Length` header so I believe it's misleading for this library to provide a way to produce them without the header.
>
> I haven't completely decided on this change however. What do you think?

I agree. Neither the HTTP protocol nor `XMLHttpRequest` is trivial, so it's very easy to shoot oneself in the foot by accidentally testing a broken scenario. It took me a number of attempts to get my tests right, mainly thanks to your helpful mock usage errors. Forcing the developer to specify the upload and download sizes in a standard-compliant way seems the right direction to me.

**Comment by berniegp** [comment]
I hadn't noticed that the command line was asking me to authenticate to NPM...

_Now_ it's published.

Thanks for the feedback!

**Comment by DanielSWolf** [comment]
Working as expected now. Thanks!
