### ISSUE TITLE
superagent

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [berniegp/mock-xmlhttprequest#7]
Feature Question

Is there any way to make this play with superagent so that send will actually make a super agent request?

**Comment by berniegp** [comment]
I don't know. I am not familiar with superagent. It this is it? https://github.com/visionmedia/superagent

Perhaps if you describe in more details what is missing from this library I will be able to provide an answer.

**Comment by BebeSparkelSparkel** [comment]
Here's a simple example:
```javascript
const { MockXhrFactory } = require('mock-xmlhttprequest'),
      XMLHttpRequest = new MockXhrFactory()

// simple request handler
const routes = require('express')()
routes.post('/url/is/this', (req, res) => {
  res.json(JSON.stringify('handled'))
})
const request = require('supertest')(routes)


XMLHttpRequest.onSend = async function (xhr) {
  try {
    const response = await request
      [xhr.method.toLowerCase()](xhr.url)
      .send(xhr.body)

    xhr.respond(still working on this)
  } catch(err) {
    console.error(err)
  }
}

const xhr = new XMLHttpRequest()
xhr.open('post', '/url/is/this')
xhr.send('data is here')
```

It will actually send the the MockXMLHttpRequest through the http server.  

I'm trying to use this for an integration test.
MockXMLHttpRequest will be in jsdom that will make requests through supertest (uses superagent) to an http server (express) and then uses MockXMLHttpRequest.respond to respond to the MockXMLHttpRequest.

**Comment by berniegp** [comment]
I would expect that calling setResponseHeaders() and setResponseBody() with whatever `response` contains would work. Which part isn't working?

Also, keep in mind the limitations of this library: https://github.com/berniegp/mock-xmlhttprequest#not-supported
It does not support the full range of features of real XMLHttpRequests

**Comment by berniegp** [comment]
Sorry, wrong button clicked! Is this still relevant?

**Comment by BebeSparkelSparkel** [comment]
I have basically figured it out. I'll send you my solution when finished. It doesn't seems like something that should be added to this project but I'll label it as an "add-in" for both incase someone else wants something similar.

Thanks for checking
